# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- build-branch

pool:
  vmImage: 'macos-latest'
stages:
- stage: "ContineousIntegration"
  jobs:
  # - job: LintAnalysis
  #   steps:
  #   - task: Gradle@2
  #     inputs:
  #       gradleWrapperFile: 'gradlew'
  #       publishJUnitResults: false
  #       javaHomeOption: 'JDKVersion'
  #       jdkVersionOption: '1.11'
  #       tasks: 'lint'
  #       sonarQubeRunAnalysis: false
  #   - task: CopyFiles@2
  #     inputs:
  #       Contents: '**/lint-results.html'
  #       TargetFolder: '$(build.artifactstagingdirectory)'
  #       OverWrite: true
  #   - task: PublishBuildArtifacts@1
  #     inputs:
  #       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #       ArtifactName: 'drop'
  #       publishLocation: Container
  # - job: UnitTests
  #   #dependsOn: LintAnalysis
  #   steps:
  #   - task: Gradle@2
  #     inputs:
  #       workingDirectory: ''
  #       gradleWrapperFile: 'gradlew'
  #       gradleOptions: '-Xmx3072m'
  #       publishJUnitResults: true
  #       testResultsFiles: '**/TEST-*.xml'
  #       javaHomeOption: 'JDKVersion'
  #       jdkVersionOption: '1.11'
  #       tasks: 'test'
  - job: Package
    #dependsOn: UnitTests
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        tasks: 'build'
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      inputs:
        Contents: '**/*.apk'
        TargetFolder: '$(build.artifactstagingdirectory)'
        OverWrite: true  
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: Container
# - stage: "ContineousDelivery"
#   jobs: 
#    - job: "Release"
#      steps:
#      - task: DownloadPipelineArtifact@2
#        inputs:
#         itemPattern: '**/app-debug.apk'
#         targetPath: '$(Pipeline.Workspace)'
#         buildType: 'current'  
#      - task: AppCenterDistribute@3
#        inputs:
#         serverEndpoint: 'SMF-Android'
#         symbolsOption: 'Android'
#         #appSlug: 'https://appcenter.ms/orgs/BPMLinks/apps/SMF-Android-Dev'
#         appSlug: 'BPMLinks/SMF-Android-Dev'
#         appFile: '$(Pipeline.Workspace)/drop/app/build/outputs/apk/debug/app-debug.apk'
#         releaseNotesOption: 'input'
#         releaseNotesInput: 'Release_$(Build.BuildNumber)'
#         destinationType: 'groups' 

           
           
           
           