# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- build-branch

pool:
  vmImage: 'macos-latest'
stages:
- stage: "ContineousIntegration"
  jobs:
  - job: LintAnalysis
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        #gradleOptions: '-Xmx3072m'
        publishJUnitResults: false
        #testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        tasks: 'lint'
        sonarQubeRunAnalysis: false
  - job: BuildJob
    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        tasks: 'test'
  
